### ISSUE TITLE
`hub` is not configured even though $GITHUB_TOKEN is set

### ISSUE THREAD

**Issue by lutzroeder** [vitorgalvao/tiny-scripts#111]
Installed from scratch without initializing `hub`. Passing the token via `${GITHUB_TOKEN}` still getting this message in cask-repair:

```
`hub` is not configured.
To do it, run `cd $(brew --repository) && hub issue`. Your Github password will be required, but is never stored.
```

**Comment by vitorgalvao** [comment]
How are you passing it?

**Comment by lutzroeder** [comment]
```
export GITHUB_TOKEN=${GH_TOKEN}
curl -H "Authorization: token ${GH_TOKEN}" https://api.github.com/repos/caskroom/homebrew-cask/forks -d ''
cask-repair --cask-version ${PACKAGE_VERSION} --blind-submit caskname
curl -H "Authorization: token ${GH_TOKEN}" -X "DELETE" https://api.github.com/repos/username/homebrew-cask
```

**Comment by vitorgalvao** [comment]
I don’t use the `GITHUB_TOKEN` method and only added due to user request. For those users, it seems to be working fine.

This is either an issue with your setup or a bug with the script, but since I’m not completely familiar with the method and I’m tired of debugging `hub`-specific problems, I’ll either entirely remove support for `GITHUB_TOKEN` *or* take a PR that fixes it in the script.

**Comment by lutzroeder** [comment]
Answer is both `${GITHUB_TOKEN}` and `${GITHUB_USER}` need to be set for this to work.
