### ISSUE TITLE
check for open PR first

### ISSUE THREAD

**Issue by brianmorton** [vitorgalvao/tiny-scripts#144]
I was going to fork to do this change and one other, but I thought you might be interested in it as well.

Before submitting the PR, check the PRs page for open PRs for the same cask name and list them (with PR title and a link) before confirming if they want to submit the new PR.

I have another change I wanted to add which I will probably do in a fork as we have discussed this before, but if the `-b` flag is passed I don't want it to ask me to confirm the url if there is no string interpolation.

**Comment by vitorgalvao** [comment]
> Before submitting the PR, check the PRs page for open PRs for the same cask name and list them (with PR title and a link) before confirming if they want to submit the new PR.

Thumbs up to that. I’ve avoided adding that functionality because none of the solutions I thought of seemed appropriate, but I think that could work.

Alternatively (just though of it, more complex but would work better), the script could detect possible duplicates, download their diffs and compare them to what would be submitted. If the same, abort and warn, if different, submit anyway.

> I have another change I wanted to add which I will probably do in a fork as we have discussed this before, but if the `-b` flag is passed I don't want it to ask me to confirm the url if there is no string interpolation.

Instead, add a new `-s/--skip-cask-url-verification`, and I’ll accept that. You’re one of the biggest users of `cask-repair`, so I’m less resistant to adding features you need.

I’ll review PRs for both of those changes.

---

On an unrelated note, in case it makes a difference in your scripts, I’ve just changed `-w, --allow-warnings` to `-w, --fail-on-warning`. Previously if you wanted to abort on errors you’d need two flags; now you just need one.

**Comment by brianmorton** [comment]
I like your thinking on diffing the patches, but that sounds a bit outside my league right now... I already do the PR checks (albeit in python) during scanning so porting that into bash seems manageable to me ;)

I will sub a separate PR for the `-s` flag - thanks.

Also thanks for the `-w` headsup.

**Comment by vitorgalvao** [comment]
Closing since it has already been accepted. Now is to wait to review the PR.
