### ISSUE TITLE
sibling to cask-repair: cask-delete

### ISSUE THREAD

**Issue by core-code** [vitorgalvao/tiny-scripts#145]
this is a wishlist item and not a bug-report. 

it would be awesome if we had a script named 'cask-delete' that could speed up sending a pull request to delete a cask.

i often stumble upon casks that no longer exist and should be removed, but the overhead of submitting a pull request manually often prevents that.

**Comment by vitorgalvao** [comment]
What’s your current process?

**Comment by core-code** [comment]
trying to create a branch in my fork and sending the pull request manually but that needs at least 5 minutes

**Comment by vitorgalvao** [comment]
What if you add something like this to your shell startup files (assuming `bash`/`zsh`):

```bash
function cask-delete {
  local cask tap
  cask="${1}"
  [[ -z "${2}" ]] && tap='homebrew-cask' || tap="homebrew-cask-${2}"

  if [[ -z "${1}" ]]; then
    echo 'Give a cask name as the first argument, and optionally a tap name as the second'
    return 1
  fi

  open "https://github.com/Homebrew/${tap}/blob/master/Casks/${cask}.rb"
}
```

Then you do something like

```bash
cask-delete alfred # Opens https://github.com/Homebrew/homebrew-cask/blob/master/Casks/alfred.rb
cask-delete firefox-nightly versions # Opens https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/firefox-nightly.rb
```

Then you need only press the delete button and create a PR from the web interface. Would that suffice=

**Comment by core-code** [comment]
awesome ;) 
( i didn't know you could do it this easily on the website and just did everything manually on the command line )

i think it would still be nice if this could be added as a standalone script to your repository for easier discovery by other users

**Comment by vitorgalvao** [comment]
I’ll have a think about it, but my initial thought is I wouldn’t want to publicise it openly. Although I really like cask deletions, I’d want for them to be submitted when it’s right (i.e. I’d rather the user makes sure before suggesting the deletion).

But I’m open to accommodating people who use my scripts regularly and *well*, such as yourself. So if you’re happy with it as is, it’s fine by me too. If someone else finds this issue and decides to also use the code, it’s also fine. Because if they did find it, they probably wanted it enough to look for it.

I’m not going to hide the code, just also not suggest it as a possibility for people that haven’t faced the need for it.

**Comment by core-code** [comment]
thanks, sounds fine with me ;)
