### ISSUE TITLE
cask-repair: allow a local install prior to commit

### ISSUE THREAD

**Issue by joshka** [vitorgalvao/tiny-scripts#17]
Heya,

Forgive me if there is an obvious technique that I'm missing here. Let's say I have v1 of a cask and I know there's v2 available. As a non-core cask room dev, I can run the script, submit a PR and wait for it to be merged. It would be nice if I could install the new version locally before the PR gets merged, but the script currently deletes the local branch prior to finishing.

In implementing this, I'm not sure which of the following would work best:

1. waiting prior to deletion for the user to install (or whatever) in a second shell
2. a --keep-local-branch flag
3. a --install flag

**Comment by vitorgalvao** [comment]
The script is about repairing casks, installing is out of scope. A core dev would have to go through the same process.

This is also not a common issue, so not something I (at least for now) plan on addressing.

**Comment by joshka** [comment]
I'm not sure I understand your answer. I want to update the cask version and then install the version that I just updated. Otherwise there's no point bothering to update the cask. How can I do this easily?

**Comment by vitorgalvao** [comment]
> Otherwise there's no point bothering to update the cask.

The point is to update it for everyone else.

**Comment by joshka** [comment]
> The point is to update it for everyone else.
Except the person doing the updating? The person who would get most immediate benefit from the update...

**Comment by vitorgalvao** [comment]
[Again](https://github.com/vitorgalvao/tiny-scripts/issues/17#issuecomment-193055091):

> The script is about repairing casks, **installing is out of scope**. A core dev would have to go through the same process.

> **This is also not a common issue**, so not something I (at least **for now**) plan on addressing.

The script is not about the person running it, it’s about contributing to the project, which is why it even saves you the trouble of making the PR. I do see your point, though, the bolded points show why the feature isn’t there.

To be honest, the script is already pushing bash too much, so I don’t really want to add a lot more to it. I want to rewrite it in another language, but that likely won’t happen for a few months.

I’m not ruling out your request, though, but I won’t do it soon.
