### ISSUE TITLE
404 when trying to repair adobe-photoshop-lightroom

### ISSUE THREAD

**Issue by danielhoherd** [vitorgalvao/tiny-scripts#173]
I am trying to update a sha on [adobe-photoshop-lightroom cask revision 0ddcd8fa6f264bf7](https://github.com/Homebrew/homebrew-cask/blob/0ddcd8fa6f264bf753e66efad7f737ac7cbc8fba/Casks/adobe-photoshop-lightroom.rb). When I attempt to install this using `brew cask install adobe-photoshop-lightroom` the downloaded URL is https://trials3.adobe.com/AdobeProducts/LTRM/6/osx10/Lightroom_6_LS11.dmg, but when I try to repair it using `cask-repair adobe-photoshop-lightroom` the downloaded URL is http://swupdl.adobe.com/updates/oobe/aam20/mac/AdobeLightroom-6.0/6.14/setup.dmg

**Comment by vitorgalvao** [comment]
Because it’s getting [its dependency](https://github.com/Homebrew/homebrew-cask/blob/0ddcd8fa6f264bf753e66efad7f737ac7cbc8fba/Casks/adobe-photoshop-lightroom.rb#L10), which [is in the versions repo](https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/adobe-photoshop-lightroom600.rb).

This is not a `cask-repair` issue, it’s the casks themselves that have a problem.

**Comment by danielhoherd** [comment]
Yeah, after digging some more I agree. I tried updating the lightroom casks to have the correct sha by hand and even their normal contribution guidelines failed to verify the casks, so I gave up.
