### ISSUE TITLE
cask-repair fails to create a pull request

### ISSUE THREAD

**Issue by JosephViolago** [vitorgalvao/tiny-scripts#18]
To start, #9, is still an issue. (TL;DR - Hotfix: `git remote set-url <github_user> git@github.com:<github_user>/homebrew-cask.git`)

`hub issue` creates a new remote to my fork set to https. Pulling from that fork (ie. `cask-repair --pull origin --push JosephViolago adafruit-arduino`) requires login (but no authentication code for MFA), and then fails. Changing that remote to ssh, fixes that problem.

But once I have access to push, I get walled off with this error:

```
Submitting…
On branch cask-repair_update-adafruit-arduino
nothing to commit, working directory clean
To git@github.com:JosephViolago/homebrew-cask.git
 ! [rejected]        cask-repair_update-adafruit-arduino -> cask-repair_update-adafruit-arduino (non-fast-forward)
error: failed to push some refs to 'git@github.com:JosephViolago/homebrew-cask.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error creating pull request: Unprocessable Entity (HTTP 422)
Missing field: "head_sha"
Missing field: "base_sha"
```

Now this is an output after I've gotten my manually-produced PR accepted, so it is difficult for me to reproduce. But I think the interesting parts is how a PR is still being attempted even after some sort of failure in the prior command.

I'll try to reproduce and record that better.

**Comment by vitorgalvao** [comment]
Have you installed via homebrew? What’s the output of `brew info cask-repair hub | grep -E '(cask-repair:|hub:)'`?

**Comment by JosephViolago** [comment]
```
$ brew info cask-repair hub | grep -E '(cask-repair:|hub:)'
vitorgalvao/tiny-scripts/cask-repair: stable 0.22.1
hub: stable 2.2.3 (bottled), HEAD
```

**Comment by vitorgalvao** [comment]
After investigating, I can see the error is from `hub`.

I’m doing some tests, but I’ll close this for now. I actually want to encourage more bug reports for this, so I can get further details. I have some ideas, but need people to actually stumble across the issue to diagnose (you have already fixed your case).

If you face it again, feel free to append to this one.

**Comment by howie** [comment]
Hi vitorgalvao

brew info cask-repair hub | grep -E '(cask-repair:|hub:)'
vitorgalvao/tiny-scripts/cask-repair: stable 0.23.1
hub: stable 2.2.3 (bottled), HEAD

Is everything correct? You can also make further manual edits (y/n/e) y
Submitting…
To git@github.com:howie/homebrew-cask.git
 ! [rejected]        cask-repair_update-dbeaver-enterprise -> cask-repair_update-dbeaver-enterprise (non-fast-forward)
error: failed to push some refs to 'git@github.com:howie/homebrew-cask.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error creating pull request: Unprocessable Entity (HTTP 422)
Missing field: "head_sha"
Missing field: "base_sha"
No commits between master and cask-repair_update-dbeaver-enterprise
Error creating pull request: Unprocessable Entity (HTTP 422)
Missing field: "head_sha"
Missing field: "base_sha"
No commits between master and cask-repair_update-dbeaver-enterprise

**Comment by vitorgalvao** [comment]
+ What happens if you try the command again now, right after it failed?
+ What’s the exact `cask-repair` command you ran?
+ In which directory are you? Are you right on the tap, or another directory?
+ What are the outputs of:
  + `git diff --shortstat`
  + `git status --porcelain`

**Comment by howie** [comment]
HI 
My  mistake ~ It' work after brew update

Thanks~

**Comment by OranShuster** [comment]
getting this error after a while a didn't use cask-repair

`brew info cask-repair hub | grep -E '(cask-repair:|hub:)'
vitorgalvao/tiny-scripts/cask-repair: stable 0.34.5
hub: stable 2.2.9 (bottled), devel 2.3.0-pre9, HEAD`
`
Is everything correct? ([y]es / [n]o / [e]dit) y
Submitting…
Error creating pull request: Unauthorized (HTTP 401)
Bad credentials
Error creating pull request: Unauthorized (HTTP 401)
Bad credentials
`
also tried running `cask-repair -d` and rerun

**Comment by vitorgalvao** [comment]
@OranShuster That’s a credentials issue, so it’s definitely not related to `cask-repair`, but `hub` (or your configuration of it).

Maybe you added 2FA or changed your password since the last time you used it.

**Comment by OranShuster** [comment]
i dont recall ever running/installing hub. i guess it's a prereq of cask-repair but i never knew it was used ( i just ran the commands from few posts up)

**Comment by vitorgalvao** [comment]
> i guess it's a prereq of cask-repair

It is.

**Comment by vitorgalvao** [comment]
> i guess it's a prereq of cask-repair

It is. Try deleting `hub`’s config (`~/.config/hub`) and try again.

**Comment by OranShuster** [comment]
Yep. now were golden
