### ISSUE TITLE
cask-repair: Cannot update Casks with language stanza

### ISSUE THREAD

**Issue by miccal** [vitorgalvao/tiny-scripts#51]
It seems that `cask-repair` is not able to handle Casks with the [`language`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/language.md) stanza.

For example, when attempting to update the [thunderbird](https://github.com/caskroom/homebrew-cask/blob/master/Casks/thunderbird.rb) Cask to version 45.4.0 using the command `cask-repair -v 45.4.0 -l origin -p miccal thunderbird`, the following output is obtained:
```
==> Downloading external files for Cask ./thunderbird.rb
==> Downloading https://ftp.mozilla.org/pub/thunderbird/releases/45.4.0/mac/en-US/Thunderbird%2045.4.0.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask thunderbird
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: d00599ab893f73cb74eafe58fae6135a5fd398b73d91822d5094831042af8061
Actual: ebba2f27fcb5f455ea2bea349ac884024d009f9e283f6205fc8a4610640988dc
File: /Users/miccal/Library/Caches/Homebrew/Cask/thunderbird--45.4.0.dmg
To retry an incomplete download, remove the file above.
shasum: ==> Note: running "brew update" may fix sha256 checksum errors: 
diff --git a/Casks/thunderbird.rb b/Casks/thunderbird.rb
index db38fad..7f44cf5 100644
--- a/Casks/thunderbird.rb
+++ b/Casks/thunderbird.rb
@@ -1,5 +1,5 @@
 cask 'thunderbird' do
-  version '45.3.0'
+  version '45.4.0'
 
   language 'de' do
     sha256 'f4daf70019bee14db81dd286fca77e6cd22f13682fd6bd65242fe52c22f0b75d'
@@ -52,7 +52,7 @@ cask 'thunderbird' do
   end
 
   language 'zh' do
-    sha256 '1e426a8df0ff6ef185eea63814517f81c24be717357b4e2b648fd50000755ee2'
+    sha256 ''
     'zh-CN'
   end
 
----------------------------------------------------------------
• ==> Auditing language: 'de'
audit for thunderbird: passed
==> Auditing language: 'en'
audit for thunderbird: passed
==> Auditing language: 'fr'
audit for thunderbird: passed
==> Auditing language: 'gl'
audit for thunderbird: passed
==> Auditing language: 'it'
audit for thunderbird: passed
==> Auditing language: 'ja'
audit for thunderbird: passed
==> Auditing language: 'nl'
audit for thunderbird: passed
==> Auditing language: 'pt'
audit for thunderbird: passed
==> Auditing language: 'ru'
audit for thunderbird: passed
==> Auditing language: 'uk'
audit for thunderbird: passed
==> Auditing language: 'zh'
audit for thunderbird: failed
 - sha256 string must be of 64 hexadecimal characters
----------------------------------------------------------------
```

If I then update the `zh` language sha256 manually and re-download, the script outputs a similar error for the next language up the list, namely `uk`.

I understand that there are only a few Casks using the `language` stanza (only 13 I believe), so I think that either:

1. Update `cask-repair` to handle these cases (which I am happy to help with);
2. Provide instructions in the Homebrew Cask docs to explain how to best update these Casks (which I am also happy to help with);
3. I am doing something wrong (quite possible!).

**Comment by vitorgalvao** [comment]
Unfortunately, this is one of those cases `cask-repair` (which is just a batch script) will not be able to handle correctly due to the variance in those casks. It’s the same issue with `url do` blocks (though I think I already detect and stop the script on those. The solution here will be to cripple `cask-repair` to not handle those.

I’ll do it on the `cask-repair` cleanup (I’ve been accumulating a list of what needs to be done).

**Comment by miccal** [comment]
Thanks for that. I believe there is only one Cask that uses a `url do` block ([audacity](https://github.com/caskroom/homebrew-cask/blob/master/Casks/audacity.rb)].

So for the Casks with a `language` stanza, the only way to update them is to check the sha256 of each language version and update them manually? If so, should we add a note to the [instructions](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask)?

**Comment by vitorgalvao** [comment]
> So for the Casks with a `language` stanza, the only way to update them is to check the sha256 of each language version and update them manually?

Yes, because there’s no way (that I’m thinking of, in a bash script) to reliably get all languages the cask uses and their organisation in a reliable way that works for all casks.

As I said, I should add a note on `cask-repair` that’ll stop changes on such casks and as such you’ll always need to manually update. When that happens, a note on the instructions should not be necessary.

**Comment by miccal** [comment]
Sound good.

**Comment by jerryskye** [comment]
Hi, I recently started using your script and I wondered if there's anything that can be done about this language stanza problem.
> Yes, because there’s no way (that I’m thinking of, in a bash script) to reliably get all languages the cask uses and their organisation in a reliable way that works for all casks.

Would it be such a big problem? I think it's worth taking a shot. I'm gonna try to come up with some way and maybe submit a PR if you don't mind. I'm not a bash genius though :smile:

**Comment by vitorgalvao** [comment]
> Would it be such a big problem?

Yes. See below.

> I think it's worth taking a shot.

It’s not. There are not enough casks with `language` to be worth the time it’ll take to implement correctly.

> I'm gonna try to come up with some way and maybe submit a PR if you don't mind.

I don’t mind and you can submit a PR, but it’s unlikely I will accept it.

> I'm not a bash genius though

And this is why.

This is not a simple issue to tackle, and it *requires* a hackish solution, due to how the script works (programatically editing the cask text file). One that *I’ll have to be the one to maintain and fix*, which will be too time consuming to be worth it.

You are, naturally, free to surprise me and prove me wrong. But if you do, please follow my style in the script. My style is pretty consistent so it should be easy to follow. It’s common that I get PRs that ignore my style to such an extent I basically have to reimplement the whole feature myself. I won’t do it in this case (again, due to its complexity)
