### ISSUE TITLE
[FR]Switch to install/upgrade a cask after submit.

### ISSUE THREAD

**Issue by yurikoles** [vitorgalvao/tiny-scripts#53]
It will be very useful since most users upgrade casks which they use by themselves and it's boring to wait for PR approval.

**Comment by vitorgalvao** [comment]
This was already discussed somewhere else. I agree and it’s on the list.

**Comment by muescha** [comment]
@yurikoles there is still this option:

```
-i, --install-cask                     Installs your updated cask after submission.
```

**Comment by vitorgalvao** [comment]
@muescha That’s the one, yes. It was added after this feature request, though. It’s quite a recent feature.

**Comment by muescha** [comment]
because i don't see this option when i used the script i would like to have an question to the interactive mode to install it now:

`Install your updated cask now? ([y]es / [n]o)` 

`y`: install the cask from `${cask_file}`
`n`: then it display a message:
 ```

   Submitted (https://github.com/caskroom/homebrew-cask/pull/30280)

   Install your updated cask now? ([y]es / [n]o)
   >n

   You decided not to install your updated cask now.

   you can install your updated cask from your local branch: 
   brew cask install https://raw.githubusercontent.com/muescha/homebrew-cask/cask-repair_update-dash/Casks/dash.rb
```

i try to create a pull request for it.

i would like to use the raw cask from pull request, but i don't know how to get the url for it :(

```
https://raw.githubusercontent.com/muescha/homebrew-cask/cc3743280181a943680a3db7690f84997b99a59e/Casks/dash.rb
```

**Comment by vitorgalvao** [comment]
> i would like to use the raw cask from pull request, but i don't know how to get the url for it :(

No point, it’s much easier to use the locally modified file (which is what it currently does).

> i try to create a pull request for it.

Please don’t, as I won’t accept it. I don’t want to create another blocking prompt. It also wouldn’t fit well with options such as `--blind-submit`, since sometimes you want to have both. If you always use `--install-cask`, then you can `alias cask-repair='cask-repair --install-cask` in your shell.

**Comment by muescha** [comment]
>  I don’t want to create another blocking prompt

i agree - an additional blocking prompt makes no sense.

i think you also against this info lines (if `--install-cask` is not used)

```
  created branch `muescha/cask-repair_update-dash` 

  Submitted (https://github.com/caskroom/homebrew-cask/pull/30280)

  you can now install your updated cask from your local branch: 
  brew cask install https://raw.githubusercontent.com/muescha/homebrew-cask/cask-repair_update-dash/Casks/dash.rb
```

**Comment by vitorgalvao** [comment]
> i think you also against this info lines (if `--install-cask` is not used)

I’d be fine with that line, actually. Just change it a bit:

```
You may upgrade the cask right now from your personal branch:
  brew cask reinstall https://raw.githubusercontent.com/muescha/homebrew-cask/cask-repair_update-dash/Casks/dash.rb
```

It should likely wait until #62, though, since before then your username isn’t in a global variable.

**Comment by vitorgalvao** [comment]
@muescha Done in https://github.com/vitorgalvao/tiny-scripts/commit/ba09a1db574993037164f91a828f132edfb6f35b and https://github.com/vitorgalvao/tiny-scripts/commit/0db5758c328c8b1f07146e2bb5ad3d77a6c28fea.
