### ISSUE TITLE
Error submitting pull request

### ISSUE THREAD

**Issue by morkro** [vitorgalvao/tiny-scripts#60]
Hello 👋 

I am trying to update my cask using `cask-repair morkro-papyrus`, but it I get the following error message:

```
diff --git a/Casks/morkro-papyrus.rb b/Casks/morkro-papyrus.rb
index 6babb63..4c1fdc7 100644
--- a/Casks/morkro-papyrus.rb
+++ b/Casks/morkro-papyrus.rb
@@ -1,10 +1,10 @@
 cask 'morkro-papyrus' do
-  version '1.0.0'
-  sha256 'cd88cd942504aa676879d86ba7c435ba8250db05525f0482a0c3812d069abf21'
+  version '1.0.2'
+  sha256 '56224eadffc9be30a240790487919406fb6ffc8e952c1446de696850b209bca8'
 
   url "https://github.com/morkro/papyrus/releases/download/#{version}/Papyrus-osx-#{version}.zip"
   appcast 'https://github.com/morkro/papyrus/releases.atom',
-          checkpoint: '8c12e03261b6509c4f1c3269fa0ab07324095c829f7cff3cc309b77c60ecc0a8'
+          checkpoint: 'f22ccbcd9ec38efaf29618ee61c2c3ede100469afeb5c16502a943e0ddeb00d1'
   name 'Papyrus'
   homepage 'https://github.com/morkro/papyrus'
 
------------------------------------------------------------------------------------------------------------------
Is everything correct? ([y]es / [n]o / [e]dit) y
Submitting…
Username for 'https://github.com': morkro
Password for 'https://morkro@github.com': 
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/morkro/homebrew-cask/'
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"

There was an error submitting the pull request. Please open a bug report on the repo for this script.
```

I have read all previously submitted issues related to that topic, but none of the solutions fixed my problem :(

**Comment by vitorgalvao** [comment]
First, try again. If that doesn’t work, please post the output of `cd "$(brew --prefix)/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks" && git remote --verbose`.

I’ll preemptively warn, though, that I’m pretty tired of debugging that specific issue. It is `hub`-related (search for the error on Google) and generally happens to certain git configs, and I can’t test them all. You can see from the other issues how much time I’ve already wasted on it.

I have a small train of thought to follow for this, but if it doesn’t work, I’ll close the issue and move on.

I won’t keep shooting in the dark. I’m happy to take a PR that squashes the problem, but don’t intend to waste much longer trying to diagnose it, since it only affects a small set of users.

**Comment by vitorgalvao** [comment]
To reiterate, I’m still waiting on

> First, try again. If that doesn’t work, please post the output of `cd "$(brew --prefix)/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks" && git remote --verbose`.

**Comment by morkro** [comment]
Thanks for the help @vitorgalvao! 🎉 
It still didn't work, so here is the output of `git remote`:

```
cask-repair     https://github.com/morkro/homebrew-cask (fetch)
cask-repair     https://github.com/morkro/homebrew-cask (push)
morkro  https://github.com.morkro/homebrew-cask (fetch)
morkro  https://github.com.morkro/homebrew-cask (push)
origin  https://github.com/caskroom/homebrew-cask (fetch)
origin  https://github.com/caskroom/homebrew-cask (push)
```

**Comment by vitorgalvao** [comment]
Unfortunately, that seems fine. So unless you can find some further details on how to diagnose/fix, I’m out of ideas.

See https://github.com/vitorgalvao/tiny-scripts/issues/18 and https://github.com/vitorgalvao/tiny-scripts/issues/20.
