### ISSUE TITLE
cask-repair: Default remotes

### ISSUE THREAD

**Issue by adityadalal924** [vitorgalvao/tiny-scripts#7]
Currently working on caskroom/CONTRIBUTING

Now, in our directions, we say to add a remote with the name "$github_user".

This ends up with them having something like (git remote -v):

```
adityadalal924	https://github.com/adityadalal924/homebrew-cask (fetch)
adityadalal924	https://github.com/adityadalal924/homebrew-cask (push)
origin	https://github.com/caskroom/homebrew-cask (fetch)
origin	https://github.com/caskroom/homebrew-cask (push)
```

However, this *isn't* the default for `cask-repair`.

Thoughts? (or should a line just be added saying to explicitly define remotes when calling the command?)

**Comment by vitorgalvao** [comment]
The problem is people might have different setups for this (your take on the instructions, of going to the actual tap and doing it there, is good).

I’m not sure having `$github_user` as a remote name is typical. I’d say `origin` and `upstream` are more so. Either way, for it to make sense with the rest of the instructions, there’s no way `cask-repair` could know which are the remotes you actually want to use (it could guess, but I’m wary of that).

What it can do is read a preference file with defaults for `push` and `pull`, so you don’t have to type those flags over and over. I’ll look into it soon.

**Comment by adityadalal924** [comment]
@vitorgalvao A preferences files seems unnecessary, I just used an (bash) alias.

Also, I think your "default" names are more standard, based on some quick browsing of stackoverflow and github help docs.

We can come back to changing contributing directions in the future if it becomes an issue, but things are probably fine the way they are for now.

**Comment by vitorgalvao** [comment]
> A preferences files seems unnecessary, I just used an (bash) alias.

Well remembered. That’s way better.
