### ISSUE TITLE
`cask-repair` forces versioned casks to use `sha256` stanza (can't use `:no_check`)

### ISSUE THREAD

**Issue by giannitm** [vitorgalvao/tiny-scripts#73]
https://github.com/caskroom/homebrew-cask/pull/33870

As shown by this pull request – every time I changed the `sha256` stanza to `:no_check`, `cask-repair` would undo it and insert the checksum instead.

**Comment by vitorgalvao** [comment]
`cask-repair` rechecks the shasums after every edit. That’s a feature, not a bug. Why would you have that `sha256` as no check?

**Comment by vitorgalvao** [comment]
The point (and original creation goal of `cask-repair`) is to easily update cask `version`s and their `sha256` as fast as possible, with just a `version`.

I don’t see why you’d want to have both a non-`:latest` `version` and a `sha256 :no_check` on that cask, especially since it has an `appcast`.

Either way, versioned casks with `:no_check` are a rarity and actively discouraged. We do not in any way encourage them, and as such there’s no point in allow them in `cask-repair`. This is a feature, not a bug.

**Comment by giannitm** [comment]
@vitorgalvao I didn't want to give this cask a checksum because the `url` is not versioned. I was worried that when the developer updates the application, the install would fail because the `sha256` would change. However, considering that we are going to be regularly checking casks with outdated appcasts, I guess that shouldn't be too much of an issue.
