### ISSUE TITLE
cask-repair not working with GitHub 2FA?

### ISSUE THREAD

**Issue by Zettt** [vitorgalvao/tiny-scripts#76]
Good morning.

I'm getting an error with casp-repair when *submitting*. 

```
Username for 'https://github.com': me
Password for 'https://me@github.com': 
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"
```

I'm trying to update the cask for resilio-sync.

**Comment by vitorgalvao** [comment]
That as nothing to do with 2FA. If you recently added 2FA, then you need to readd your credentials (delete `~/.config/hub` and try again).

Otherwise, as I’ve mentioned on several occasions, I won’t keep debugging that specific issue. It is `hub`-related (search for the error on Google) and generally happens with certain git configs. I can’t test them all. You can see from the other issues (e.g. #20) how much time I’ve already wasted on it.

Unfortunately, I won’t keep shooting in the dark. I’m happy to take a PR that squashes the problem for good, but don’t intend to waste much longer trying to diagnose it. It only affects a small set of users and is no longer worth the commitment and frustration.
