### ISSUE TITLE
`cask-repair` failures

### ISSUE THREAD

**Issue by adityadalal924** [vitorgalvao/tiny-scripts#8]
Going to post failures for `cask-repair` here, as i'm verifying your PRs

----------------

Fails on glyphs.rb (version 2.2.2-825)

```
Type the new version (or leave blank to abort)
> 2.2.2-825
==> Downloading external files for Cask ./glyphs.rb
==> Downloading https://updates.glyphsapp.com/Glyphs2.2.2-825.zip
######################################################################## 100.0%
==> No checksum defined for Cask glyphs, skipping verification
==> Success! Downloaded to -> /Library/Caches/Homebrew/glyphs-2.2.2-825.zip
curl: (3) <url> malformed
audit for glyphs: passed
Is everything correct? You can also make further manual edits (y/n/e) 
```

There *is* a checksum, and it should be verifying it, also a curl error.

**Comment by vitorgalvao** [comment]
> There is a checksum, and it should be verifying it

If you notice, every cask you update with `cask-repair` will have that message. It’s homebrew-cask outputting that, not `cask-repair`. What’s happening is I need to [temporarily set casks as `:no_check` before fetching, to avoid mismatch errors](https://github.com/vitorgalvao/tiny-scripts/blob/24aa96420cecdd5192a04d5c751a714cfb13fc32/cask-repair#L86). Unfortunately, there’s no way to get rid of that message without grabbing all other messages as well, including the download bar, which means that to get rid of that message, your terminal would look like it was frozen until the download finished.

Same for the `curl` error. That message is from `brew cask fetch`. It was a temporary network error, most likely.

Closing in case there aren’t any other failures (since there’s nothing to do with that one), but please do post others you encounter as new comments on this issue.

**Comment by adityadalal924** [comment]
I do still consistently get `curl: (3) <url> malformed` - I have a custom `.curlrc`

No errors if using `curl --silent "{{appcast_url_here}}" | shasum --algorithm 256 | awk '{ print $1 }'`


.curlrc:
```
user-agent = "Mozilla/5.0 (Windows NT 6.1; rv:31.0) Gecko/20100101 Firefox/31.0"
referer = ";auto"
connect-timeout = 10
progress-bar
show-error
remote-time
ipv4
```

**Comment by vitorgalvao** [comment]
Found the issue. Everything was still working, though, it was just `show-error` in your `.curlc` that showed that message. It’s now more robust, and that error shouldn’t appear.

**Comment by adityadalal924** [comment]
SourceForge URLs still don't seem to be playing nice - they abort before the download is complete and a (wrong) shasum is used.

Example for testing: `davmail`, new version is `4.7.1-2416`, correct shasum should be `8a91ac4125f7351a39a4ef5840148c87421b76d6128dad80694a78490612bfca`

Any other logs I can give you to make finding the issue easier?

**Comment by vitorgalvao** [comment]
That is definitely the fault of `.curlrc`. Try this (leave the cask as it currently is): `brew cask fetch --force davmail`.

You should see the shasum is wrong, even in the current cask. Then remove your `.curlrc` and try again. You should see it pass.

All `cask-repair` is doing is that exact `brew cask fetch --force` command, and then getting the shasum on the downloaded file. `.curlrc` issues are not something it can (or should) fix.

**Comment by adityadalal924** [comment]
I have no particular attachment to my `.curlrc` - will remove it and do some more testing.

It looks like Homebrew ignores it entirely, anyway - https://github.com/Homebrew/homebrew/issues/9027

**Comment by vitorgalvao** [comment]
> It looks like Homebrew ignores it entirely, anyway - https://github.com/Homebrew/homebrew/issues/9027

Not exactly, [they went back on that decision](https://github.com/Homebrew/homebrew/issues/13836).
